version: '3.8'

services:
  ocr-service:
    build: .
    container_name: ocr-service
    ports:
      - "8000:8000"

    environment:
      OLLAMA_API_URL: "http://host.docker.internal:11434"   # Mac/Windows i√ßin OK
      OLLAMA_MODEL: "gemma3:4b"
      UPLOAD_DIR: "/app/uploads"
      DEBUG: "False"

    volumes:
      - ./app/uploads:/app/uploads

    env_file:
      - .env

    restart: unless-stopped
